<a href="https://colab.research.google.com/github/Akash-280419/DATA-SCIENCE-PRACTICAL/blob/main/practical3_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
m=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(np.triu(m)) #upper diagonal

[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [ ]:
print(np.triu(m,-1))

[[1 2 3]
 [4 5 6]
 [0 8 9]]


In [ ]:
print(np.triu(m,-2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
