<a href="https://colab.research.google.com/github/Akash-280419/DATA-SCIENCE-PRACTICAL/blob/main/practical2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#practical 2.1
#write a numpy program to give sort array by the column
#import numpy
import numpy as np
print("orignal array:")
nums=np.random.randint(0,10,(3,3))
print(nums)

orignal array:
[[4 8 7]
 [1 7 9]
 [0 1 0]]


In [3]:
#sort the nth column in the array
print("\n Sort thr said array by the nth column:")
print(nums[nums[:,1].argsort()])


 Sort thr said array by the nth column:
[[0 1 0]
 [1 7 9]
 [4 8 7]]


In [4]:
#2.2
nums=np.array([[70,50,20,12,30,-11,60,50,40,25,35]])
print("orignal array :")
print(nums)


orignal array :
[[ 70  50  20  12  30 -11  60  50  40  25  35]]


In [6]:
print("\nAfter partitioning on 4 the position:")
print(np.partition(nums,4))


After partitioning on 4 the position:
[[ 12  20 -11  25  30  35  60  50  40  50  70]]
